window.bootstrap = require("bootstrap/dist/js/bootstrap.bundle.js");
import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import "./css/bootstrap.min.css";
import "./css/owl.carousel.min.css";
import "./css/animate.min.css";
import "./css/magnific-popup.css";
import "./css/fontawesome-all.min.css";
import "./css/flaticon.css";
import "./css/jquery-ui.css";
import "./css/meanmenu.css";
import "./css/slick.css";
import "./css/default.css";
import "./css/style.css";
import "./css/responsive.css";
import "./css/slick.css";
createApp(App).use(router).mount("#app");
